services:
  postgres:
    image: postgres
    container_name: weather-postgres
    env_file:
      - .docker.env
    ports:
      - "2345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: weather-redis
    ports:
      - "9736:6379"

volumes:
  postgres_data: